### ISSUE TITLE
Route exposes only port 5701

### ISSUE THREAD

**Issue by rafabene** [vert-x3/vertx-openshift-s2i#2]
I created a service running[1] on port 8080 but the route exposes port 5701 instead. I had to manually edit the route yaml file to have access to por 8080 in the generated route

[1]https://github.com/redhat-helloworld-msa/aloha

**Comment by cescoffier** [comment]
Which Yaml file did you edit ? `vertx-s2i-all` ?

**Comment by rafabene** [comment]
Nope. The generated route/aloha

**Comment by cescoffier** [comment]
oh I see, it does not pick the right port of the service. Do you know how the selection is made (maybe it should be 2 services and not one with 2 ports).

**Comment by rafabene** [comment]
My guess would be using a multi-port services as described by the Kubernetes Services spec: http://kubernetes.io/docs/user-guide/services/#multi-port-services

**Comment by cescoffier** [comment]
The route has been removed, so no problem anymore.
