### ISSUE TITLE
Apache mirror is offline

### ISSUE THREAD

**Issue by rafabene** [vert-x3/vertx-openshift-s2i#3]
When trying to build the image, the download of maven from http://apache.rediris.es/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz gets time-out. 

Error: 

`
gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
F0407 21:40:55.605241       1 builder.go:59] Build error: The command '/bin/sh -c yum install -y --enablerepo=centosplus     tar unzip bc which lsof java-1.8.0-openjdk java-1.8.0-openjdk-devel &&     yum clean all -y &&     (curl -0 http://apache.rediris.es/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz |     tar -zx -C /usr/local) &&     mv /usr/local/apache-maven-$MAVEN_VERSION /usr/local/maven &&     ln -sf /usr/local/maven/bin/mvn /usr/local/bin/mvn &&     curl -sL -0 https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip -o /tmp/gradle-${GRADLE_VERSION}-bin.zip &&     unzip /tmp/gradle-${GRADLE_VERSION}-bin.zip -d /usr/local/ &&     rm /tmp/gradle-${GRADLE_VERSION}-bin.zip &&     mv /usr/local/gradle-${GRADLE_VERSION} /usr/local/gradle &&     ln -sf /usr/local/gradle/bin/gradle /usr/local/bin/gradle &&     mkdir -p /opt/openshift && chmod -R a+rwX /opt/openshift &&    mkdir -p /opt/app-root/source && chmod -R a+rwX /opt/app-root/source &&     mkdir -p /opt/s2i/destination && chmod -R a+rwX /opt/s2i/destination &&     mkdir -p /opt/app-root/src && chmod -R a+rwX /opt/app-root/src &&     mkdir -p /opt/.m2 && chmod -R a+rwX /opt/.m2' returned a non-zero code: 2
`

**Comment by cescoffier** [comment]
The mirror is down, thanks for reporting !

**Comment by cescoffier** [comment]
Fixed in the `initial-work` branch

**Comment by rafabene** [comment]
Thanks
