### ISSUE TITLE
Failed to build vertx-s2i-

### ISSUE THREAD

**Issue by rafabene** [vert-x3/vertx-openshift-s2i#8]
I ran CDK 2.1 and executed "oc create -f https://raw.githubusercontent.com/vert-x3/vertx-openshift-s2i/master/vertx-s2i-all.json".

In the logs for the vertx-s2i-1 build I see the following error: 

> I0817 14:38:30.422674       1 source.go:197] Downloading "https://github.com/cescoffier/vertx-s2i.git" ...
> Step 1 : FROM centos@sha256:643a8696ecdaacb44e9d3868fcd8168588d21a923dc58bc1c74e25c3884d82f5
> Trying to pull repository registry.access.redhat.com/centos ... failed
> Trying to pull repository docker.io/library/centos ... failed
> F0817 14:38:34.131755       1 builder.go:204] Error: build error: manifest unknown: manifest unknown

This seems to be related to a docker-hub image format change. Any image should be published using Docker 1.9

**Comment by gnunn1** [comment]
Same issue here, I tried going through the steps here but no joy:

https://access.redhat.com/solutions/2391351

Any advice appreciated.

**Comment by cescoffier** [comment]
Thanks for reporting, gonna have a look. 

Maybe updating the Centos image (version) could fix it ?

**Comment by cescoffier** [comment]
@rafabene any idea why I had to add `config.ssh.insert_key = false` to the Openshift `Vagrantfile` ?

**Comment by cescoffier** [comment]
I've fixed the issue by switching to an openshift images (instead of the "raw" centos) image.

**Comment by gnunn1** [comment]
@cescoffier Thanks for the fix. With respect  insert_key question, any chance you are running Vagrant 1.8.5? It has issue https://github.com/mitchellh/vagrant/issues/7610 where it doesn't insert a new SSH key properly when first starting up. I ended up applying the associated fix but many folks were saying setting insert_key to false fixes it as well.

**Comment by cescoffier** [comment]
@gnunn1 yes...:

```
> vagrant version
Installed Version: 1.8.5
Latest Version: 1.8.5
```

I should not update my tool without looking to the release notes ;-)
